# Generated by Django 2.2.4 on 2019-08-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='record_label',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='albums',
            name='year',
            field=models.CharField(default='', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='albums',
            name='genre',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='albums',
            name='logo',
            field=models.CharField(default='', editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='albums',
            name='name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='albums',
            name='title',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
