# Generated by Django 2.2.4 on 2019-08-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190820_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='albums',
            name='logo',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='albums',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='albums',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='albums',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='format',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
