# Generated by Django 2.2.4 on 2019-09-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190820_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
