# Generated by Django 2.2.4 on 2019-11-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
